### ISSUE TITLE
rtl mode problem 

### ISSUE THREAD

**Issue by ppeyman** [swissup/module-rtl#1]
when i change the mode to rtl doesn`t works 
and show like bellow 

![image](https://user-images.githubusercontent.com/13271466/186185884-63d57328-8b5b-425b-9ca8-fab0ab584019.png)

**Comment by vovayatsyuk** [comment]
Thanks for reporting! 

The issue was in the Breeze Blank theme. [The fix](https://github.com/breezefront/theme-frontend-breeze-blank/commit/e4c996fa4ed3fc1a9dd7f5d3306e9f73032a3773) will be included in the next release.

**Comment by vovayatsyuk** [comment]
Made a few more RTL fixes in https://github.com/breezefront/module-breeze and https://github.com/breezefront/theme-frontend-breeze-blank.
