### ISSUE TITLE
breadcrumb icon show mistake navigate

### ISSUE THREAD

**Issue by ppeyman** [swissup/module-rtl#2]
another one breadcrumb icon show mistake navigate : 

![image](https://user-images.githubusercontent.com/13271466/186200460-b232dedf-be19-4d4e-a55e-c7b56941647e.png)

**Comment by vovayatsyuk** [comment]
Already fixed in one of commits in previous issue :)

**Comment by ppeyman** [comment]
> Already fixed in one of commits in previous issue :)

i upgrade scroller removed but @icon-chevron show right again it should show left

**Comment by vovayatsyuk** [comment]
Are you sure you get all of the fixes? Breadcrumbs were fixed in this particular commit https://github.com/breezefront/theme-frontend-breeze-blank/commit/07d2c254df253cd71c10d5807f4888731b9e26c6

**Comment by ppeyman** [comment]
> Are you sure you get all of the fixes? Breadcrumbs were fixed in this particular commit [breezefront/theme-frontend-breeze-blank@07d2c25](https://github.com/breezefront/theme-frontend-breeze-blank/commit/07d2c254df253cd71c10d5807f4888731b9e26c6)


i installed last version 1.1.7 doesn`t solve both of them breadcrumb and scroll 
you mean in next version will be come fixed items ?

**Comment by vovayatsyuk** [comment]
Yes, all of these fixes are not released yet, so you need to wait for the next release.

**Comment by ppeyman** [comment]
> Yes, all of these fixes are not released yet, so you need to wait for the next release.

thanks sorry i made mistake and think on this version is available 
thanks i fix it manually
