### ISSUE TITLE
Install of swissup/module-rtl failed

### ISSUE THREAD

**Issue by Daniel-Zadora** [swissup/module-rtl#3]
composer require swissup/module-rtl

 [Exception]
  Higher matching version 2.5.2 of swissup/module-breeze was found in public repository packagist.org
                               than 2.5.1 in private https://repo.magento.com. Public package might've been taken
   over by a malicious entity,
                               please investigate and update package requirement to match the version from the private repository

**Comment by vovayatsyuk** [comment]
We've updated swissup/module-breeze at the magento marketplace, it should work fine now.
